{
 "title": "Cassandra-new",
 "description": "Monitoring Cassandra with Prometheus using JXM exporter",
 "tags": [ "cassandra" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(up{job=~\"cassandra_.*\"}, instance)"
   },
   { "name": "interval", "label": "interval", "query": "30s,1m,5m,1h,6h,1d" }
  ]
 },
 "panels": [
  {
   "title": "Node status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "up{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "ClientWrite avg duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "(cassandra_clientrequest_latency_mean{instance=\"$instance\",type=~\"Write\"} > 0) / 1000"
    }
   ]
  },
  {
   "title": "ClientRead avg duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "(cassandra_clientrequest_latency_mean{instance=\"$instance\",type=~\"Read\"} > 0) / 1000"
    }
   ]
  },
  {
   "title": "JVM Heap usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "expr": "(jvm_memory_bytes_used{area=\"heap\",instance=\"$instance\"} / jvm_memory_bytes_max{area=\"heap\", instance=\"$instance\"}) * 100"
    }
   ]
  },
  {
   "title": "Pending compactions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "cassandra_compaction_pendingtasks{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Pending threads",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(cassandra_threadpools_pendingtasks{instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "ParNew GC duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$instance\",gc=\"ParNew\"}[$interval]) / rate(jvm_gc_collection_seconds_count{instance=\"$instance\",gc=\"ParNew\"}[$interval])"
    }
   ]
  },
  {
   "title": "OldGen GC duration",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$instance\",gc=\"ConcurrentMarkSweep\"}[$interval]) / rate(jvm_gc_collection_seconds_count{instance=\"$instance\",gc=\"ConcurrentMarkSweep\"}[$interval])"
    }
   ]
  },
  {
   "title": "Unavailable exceptions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(cassandra_clientrequest_unavailables{clientrequest=~\"Read|Write\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Timeout exceptions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(cassandra_clientrequest_timeouts{clientrequest=~\"Write|Read\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Connection timeouts",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "rate(cassandra_connection_totaltimeouts{instance=~\"$instance\"}[$interval])"
    }
   ]
  },
  {
   "title": "Coordinator level stats (data can be R/W using other nodes)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 }
  },
  {
   "title": "Writes / sec $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_clientrequest_latency_count{instance=\"$instance\",type=~\"Write.*\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Reads / sec $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_clientrequest_latency_count{instance=\"$instance\",type=~\"Read.*\"}[$interval])",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Avg write latency $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "ms", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "(cassandra_clientrequest_latency_mean{instance=\"$instance\",type=~\"Write.*\"} > 0) / 1000",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Avg read latency $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "ms", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "(cassandra_clientrequest_latency_mean{instance=\"$instance\",type=~\"Read.*\"} > 0) / 1000",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "95thPercentile write latency $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "ms", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "(cassandra_clientrequest_latency_95thpercentile{instance=\"$instance\",type=~\"Write.*\"}> 0) / 1000",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "95thPercentile read latency $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "ms", "label": "milliseconds" }
   ],
   "targets": [
    {
     "expr": "(cassandra_clientrequest_latency_95thpercentile{instance=\"$instance\",type=~\"Read.*\"}) / 1000",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Requests to R/W on current node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 }
  },
  {
   "title": "Writes Latency Count $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_writelatency_count{instance=~\"$instance\",keyspace!~\"system.*|eit\"}",
     "legendFormat": "{{keyspace}}: {{table}}"
    }
   ]
  },
  {
   "title": "Reads Latency Count $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cassandra_table_readlatency_count{instance=~\"$instance\",keyspace!~\"system.*|eit\"}",
     "legendFormat": "{{keyspace}}: {{table}}"
    }
   ]
  },
  {
   "title": "Avg write latency $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(cassandra_table_writelatency_mean{instance=~\"$instance\",keyspace!~\"system.*|eit\"} > 0) / 1000",
     "legendFormat": "{{keyspace}}: {{table}}"
    }
   ]
  },
  {
   "title": "Avg read latency $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(cassandra_table_readlatency_mean{instance=~\"$instance\",keyspace!~\"system.*|eit\"} > 0) / 1000",
     "legendFormat": "{{keyspace}}: {{table}}"
    }
   ]
  },
  {
   "title": "95thPercentile write latency $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(cassandra_table_writelatency_95thpercentile{instance=~\"$instance\",keyspace!~\"system.*|eit\"} > 0) / 1000",
     "legendFormat": "{{keyspace}}: {{table}}"
    }
   ]
  },
  {
   "title": "95thPercentile read latency $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(cassandra_table_readlatency_95thpercentile{instance=~\"$instance\",keyspace!~\"system.*|eit\"} > 0) / 1000",
     "legendFormat": "{{keyspace}}: {{table}}"
    }
   ]
  },
  {
   "title": "Keyspace Range latency $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "(cassandra_columnfamily_rangelatency_mean{instance=\"$instance\"})  / 1000",
     "legendFormat": "RangeLatency"
    }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "GC count / sec $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_count{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC avg time $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 65 },
   "yaxes": [
    { "format": "s", "label": "seconds" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{instance=\"$instance\"}[$interval]) / rate(jvm_gc_collection_seconds_count{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "Heap usage $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 74 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"heap\",instance=\"$instance\"}",
     "legendFormat": "Used heap size"
    },
    {
     "expr": "jvm_memory_bytes_max{area=\"heap\", instance=\"$instance\"}",
     "legendFormat": "Max heap size"
    }
   ]
  },
  {
   "title": "Non-Heap usage $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 74 },
   "yaxes": [
    { "format": "decbytes", "label": "Memory in Mb's" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{area=\"nonheap\",instance=\"$instance\"}",
     "legendFormat": "Used non-heap size"
    },
    {
     "expr": "jvm_memory_bytes_committed{area=\"nonheap\",instance=\"$instance\"}",
     "legendFormat": "Commited non-heap size"
    }
   ]
  },
  {
   "title": "Memory Pool used $instance",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 83 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_pool_bytes_used{instance=\"$instance\"}",
     "legendFormat": "{{pool}}"
    }
   ]
  },
  {
   "title": "Threads count $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 95 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{instance=\"$instance\"}",
     "legendFormat": "Threads count"
    }
   ]
  },
  {
   "title": "Open file descriptors $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 95 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "process_open_fds{instance=\"$instance\"}",
     "legendFormat": "Open file descriptors"
    }
   ]
  },
  {
   "title": "Requests errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 104 },
   "collapsed": true,
   "panels": [
    {
     "title": "Unavailable exceptions / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 105 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_clientrequest_unavailables[$interval]) > 0",
       "legendFormat": "{{clientrequest}}"
      }
     ]
    },
    {
     "title": "Timeout exceptions / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 105 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_clientrequest_timeouts[$interval]) > 0",
       "legendFormat": "{{clientrequest}}"
      }
     ]
    },
    {
     "title": "Connection timeouts / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 112 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_connection_totaltimeouts[$interval]) > 0",
       "legendFormat": "Connection timeouts"
      }
     ]
    },
    {
     "title": "Storage exceptions / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 112 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_storage_exceptions[$interval])",
       "legendFormat": "Expections"
      }
     ]
    },
    {
     "title": "Speculative retries / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 119 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_columnfamily_speculativeretries{keyspace=~\".+\",instance=~\"$instance\"}[$interval]) > 0",
       "legendFormat": "{{keyspace}}:{{columnfamily}}"
      }
     ]
    }
   ]
  },
  { "title": "DIsk usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 105 } },
  {
   "title": "Top10 tables by size $instance",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(cassandra_columnfamily_totaldiskspaceused{keyspace=~\".+\",instance=~\"$instance\"}) by (keyspace,columnfamily) > 0)",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "Total disk usage $instance",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 106 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_storage_load{instance=~\"$instance\"}",
     "legendFormat": "Total disk usage"
    }
   ]
  },
  { "title": "Compaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 121 } },
  {
   "title": "Top10 SSTables count $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "topk(10,cassandra_columnfamily_livesstablecount{keyspace=~\".+\",instance=~\"$instance\"}) > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "Pending tasks count $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 122 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cassandra_compaction_pendingtasks{instance=~\"$instance\"}",
     "legendFormat": "Pending tasks"
    }
   ]
  },
  {
   "title": "Completed tasks count $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 122 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_compaction_completedtasks{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Completed tasks"
    }
   ]
  },
  {
   "title": "Bytes compacted $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 130 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_compaction_bytescompacted{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Bytes compacted"
    }
   ]
  },
  {
   "title": "Completed compactions $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_compaction_totalcompactionscompleted{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Compactions completed"
    }
   ]
  },
  {
   "title": "SSTablesPerRead $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 130 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_columnfamily_sstablesperreadhistogram{keyspace=~\".+\",instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  { "title": "Connected clients", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 } },
  {
   "title": "Client count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 138 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_client_connectednativeclients{instance=\"$instance\"}",
     "legendFormat": "Native"
    },
    {
     "expr": "cassandra_client_connectedthriftclients{instance=\"$instance\"}",
     "legendFormat": "Thrift"
    }
   ]
  },
  { "title": "Hinted handoff", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 145 } },
  {
   "title": "Total hints / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_storage_totalhints{instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "Total hints count"
    }
   ]
  },
  {
   "title": "Total hints in progress / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 146 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_storage_totalhintsinprogress{instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "Total hints in progress"
    }
   ]
  },
  { "title": "Bloom filter", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 153 } },
  {
   "title": "False positives $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 154 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_bloomfilterfalsepositives{keyspace=~\".+\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "False ratio $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 154 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_bloomfilterfalseratio{keyspace=~\".+\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "Disk usage $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 161 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_bloomfilterdiskspaceused{keyspace=~\".+\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "OffHeap memory used $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 161 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_bloomfilteroffheapmemoryused{keyspace=~\".+\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  { "title": "Thread pools", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 168 } },
  {
   "title": "Completed tasks / sec $instance",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 169 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_threadpools_completedtasks{instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{threadpools}}"
    }
   ]
  },
  {
   "title": "Pending tasks / sec $instance",
   "type": "graph",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 169 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_threadpools_pendingtasks{instance=~\"$instance\"} > 0",
     "legendFormat": "{{threadpools}}"
    }
   ]
  },
  {
   "title": "Dropped messages / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 182 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_droppedmessage_dropped{instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{droppedmessage}}"
    }
   ]
  },
  {
   "title": "Active tasks $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 182 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_threadpools_activetasks{instance=~\"$instance\"} > 0",
     "legendFormat": "{{threadpools}}"
    }
   ]
  },
  {
   "title": "Total blocked tasks / sec $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 189 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_threadpools_totalblockedtasks{instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{threadpools}}"
    }
   ]
  },
  {
   "title": "Currently blocked tasks $instance",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 189 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_threadpools_currentlyblockedtasks{instance=~\"$instance\"} > 0",
     "legendFormat": "{{threadpools}}"
    }
   ]
  },
  { "title": "Key cache", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 196 } },
  {
   "title": "KeyCache Hit Rate $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 197 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "cassandra_cache_hitrate{instance=\"$instance\"}",
     "legendFormat": "{{hit rate}}"
    }
   ]
  },
  {
   "title": "Cache size $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 197 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_cache_size{instance=\"$instance\"}",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache hits / sec $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 197 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_cache_hits{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache requests / sec $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 9, "x": 0, "y": 205 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_cache_requests{instance=\"$instance\"}[$interval])",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  {
   "title": "Cache entries $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 9, "y": 205 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_cache_entries{instance=\"$instance\"}",
     "legendFormat": "{{cache}}"
    }
   ]
  },
  { "title": "Memtables", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 214 } },
  {
   "title": "Top10 memtables by table size $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 215 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "topk(10,sum(cassandra_columnfamily_memtablelivedatasize{keyspace=~\".+\",instance=~\"$instance\"}) by (keyspace,columnfamily) > 0)",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "Memtables columns count $instance",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 215 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_memtablecolumnscount{keyspace=~\".+\",instance=~\"$instance\"} > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "Total memtables size $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 223 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "cassandra_columnfamily_memtableonheapsize{keyspace=\"\",instance=~\"$instance\"}",
     "legendFormat": "OnHeap"
    },
    {
     "expr": "sum(cassandra_columnfamily_memtableoffheapsize{keyspace=\"\",instance=~\"$instance\"})",
     "legendFormat": "OffHeap"
    }
   ]
  },
  {
   "title": "Memtables switch count / sec $instance",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 223 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(cassandra_columnfamily_memtableswitchcount{keyspace=~\".+\",instance=~\"$instance\"}[$interval]) > 0",
     "legendFormat": "{{keyspace}}:{{columnfamily}}"
    }
   ]
  },
  {
   "title": "CQL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 232 },
   "collapsed": true,
   "panels": [
    {
     "title": "CQL regular statements / sec $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_cql_regularstatementsexecuted{instance=~\"$instance\"}[$interval])",
       "legendFormat": "Regular statements"
      }
     ]
    },
    {
     "title": "CQL prepared statements $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 68 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(cassandra_cql_preparedstatementsexecuted{instance=~\"$instance\"}[$interval])",
       "legendFormat": "Prepared statements"
      }
     ]
    }
   ]
  },
  {
   "title": "Snapshots",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 233 },
   "collapsed": true,
   "panels": [
    {
     "title": "Snapshots size $instance",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 69 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "cassandra_columnfamily_snapshotssize{keyspace=~\".+\",instance=~\"$instance\"} > 0",
       "legendFormat": "{{keyspace}}:{{columnfamily}}"
      }
     ]
    }
   ]
  }
 ]
}